export enum TokenType {
    // SINGLE-CHARACTER TOKENS.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    // LITERAL
    IDENTIFIER, STRING, NUMBER,
    // KEYWORDS
    AND, ELSE, FALSE, FN, FOR, IF, NIL, OR,
    PRINT, RETURN, TRUE, LET, WHILE, FROM,
    EOF
}